baseURL = 'https://pearrybyte.github.io/recordofmyyouth/'
languageCode = 'en-us'
title = 'Record Of My Youth'
theme = 'hugo-theme-re-terminal'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
  customCSS = ["css/custom.css"]